### ISSUE TITLE
missing required options: body after upgrade to 4.0.2

### ISSUE THREAD

**Issue by AlithAnar** [hypermodules/gh-release#106]
I've got package.json and CHANGELOG.md in a root folder. Everything is set up as before. When I type gh-release without any options, I've got preview with empty body. When I hit `yes` then error occures: missing required options: body.

Docu says that All options have their defaults and can be omitted like body:

`body: '* init\n',`

What am I missing from latest breaking changes?

**Comment by bcomnes** [comment]
Possibly a bug with the new version.  Can you post an example repo/gist?

**Comment by AlithAnar** [comment]
Ok found an issue with my changelog file. 

[](https://tc3-img-dev.s3.eu-central-1.amazonaws.com/b10327c5cae2cc2481ce654226727c77977175bfe8b2498f307f8d1c32034df6)

Don't know if It should be some parse error or parsing went ok and just body wasn't matched correctly

**Comment by bcomnes** [comment]
Cool, glad you figured it out.  

Closing in favor of 107
