### ISSUE TITLE
The yargs@17 library requires too high node version, can it be changed to rely on 16？

### ISSUE THREAD

**Issue by janryWang** [hypermodules/gh-release#129]

**Comment by bcomnes** [comment]
What version of node are you targeting?

**Comment by janryWang** [comment]
> What version of node are you targeting?

>= 10.x

**Comment by bcomnes** [comment]
@janryWang Node 10 is EOL, so I don't think we have any intention of supporting it any longer.  However it does look like the change to yargs@17 went out on a non major release, so sorry if that broke on you.  

@ungoldman Looks like this went out in 5.x.  What do you think about me rolling back yargs, dong a 5.x patch, then updating it again on a 6.0.0 release. @janryWang that way you will get the latest changes, on 5.x and you can resume supported development when you can upgrade node.

**Comment by janryWang** [comment]
I very much agree with your approach, 5.x guarantees that no Break Change is reasonable

**Comment by bcomnes** [comment]
K looks like @jgravois is on board, so I'll do that.

**Comment by bcomnes** [comment]
ok, rolled back in 5.0.2.  When you upgrade to node > 10, it would be great to have you on 6+ :) Thanks for the heads up.

**Comment by jgravois** [comment]
thx @bcomnes! 🙏
