### ISSUE TITLE
Feature request: Add a progress indicator

### ISSUE THREAD

**Issue by zeke** [hypermodules/gh-release#49]
It would be nice to know how far along things are when uploading assets with a release.

I ended up staring at the screen for a while with fingers crossed...

![screen shot 2017-02-01 at 4 57 37 pm](https://cloud.githubusercontent.com/assets/2289/22532947/bf73d248-e89f-11e6-855c-ef2757b7fc11.png)

**Comment by bcomnes** [comment]
This one looked kinda cool https://github.com/gagle/node-status-bar  

I could maybe try to add that.

**Comment by ungoldman** [comment]
Sounds good, PR welcome if I don't get to it first!

**Comment by ungoldman** [comment]
@zeke I invited you as a collaborator ([open open source rules](https://github.com/ungoldman/gh-release/blob/master/CONTRIBUTING.md#project-governance)) -- feel free to improve this module as you see fit (same goes for @bcomnes who is already a collaborator). 😁

**Comment by ungoldman** [comment]
Forgot to mention the assets stuff is managed by a separate module made by fellow collaborator @paulcpederson -- https://github.com/paulcpederson/gh-release-assets

**Comment by zeke** [comment]
> Maybe hypermodules?

👍

**Comment by ungoldman** [comment]
Took a quick look:

> gh-release-assets also emits the following events:
> 
> - upload-asset - {name} - Emits before an asset file starts uploading. Emits the name of the file.
> - upload-progress - {name, progress} - Emits while a file is uploading. Emits the name of the file, and a progress object from progress-stream.
> - uploaded-asset - {name} - Emits after an asset file is successfully uploaded. Emits the name of the file.

Should be pretty easy to add handlers to these events (see https://github.com/paulcpederson/gh-release-assets/blob/ab4e6d5dcf16ee124aef77276b3b7a2c4a06a5e3/test/index.js#L53-L61 for example)

**Comment by zeke** [comment]
Hey @bcomnes or @ungoldman can you add me to the hypermodules org? 🙏

**Comment by bcomnes** [comment]
Oh yeah definately

**Comment by bcomnes** [comment]
Sent

**Comment by tjaneczko** [comment]
Will take this on when I get some free time, should be a nice enhancement!

**Comment by tjaneczko** [comment]
Did a bit of research on this over the weekend, it looks like using something like [gauge](https://github.com/iarna/gauge) or [cli-progress](https://github.com/AndiDittrich/Node.CLI-Progress) would be easiest as it allows you to easily update the progress bar without needing to use a stream (which [node-status-bar](https://github.com/gagle/node-status-bar) needs).  gauge looks to be really easy to use, and it's used by npm itself, so it might be nice to go with that.  Anyone have any other thoughts or ideas on this?  If not, I should be able to get a PR for this sometime this week 😃

**Comment by paulcpederson** [comment]
👌

**Comment by bcomnes** [comment]
Stream progress bars are difficult without knowing the total size of the stream operation in advance.  I've been brainstorming a [folder-walker](https://github.com/karissa/folder-walker) with progress lookahead for folder walking based operations.  Haven't had time yet though.

**Comment by ungoldman** [comment]
@tjaneczko gauge looks fine, let's go with that

**Comment by tjaneczko** [comment]
Unfortunately I've been super busy these past couple of weeks and haven't had a chance to finish this up yet, but I should hopefully have a PR ready soon!

**Comment by ungoldman** [comment]
@tjaneczko story of my life 😉

**Comment by tjaneczko** [comment]
Finally was able to get some free time and got this working in PR #80 .  Looks really slick when uploading multiple assets or large assets :smile:

**Comment by ungoldman** [comment]
Resolved in #80, released in `3.4.0`. Thanks @tjaneczko!
