### ISSUE TITLE
Defaults don't set (Node API) & wrong tests

### ISSUE THREAD

**Issue by roman0x58** [hypermodules/gh-release#55]
Hi there! I trying to use `gh-release` as Node API, but defaults don't set correctly, it failed without all parameters set in the config object. Further I try to run test on this repo, and the all tests are passed. I think a deepEquality test is wrong when you're asserting the two error objects, because those should have the different stack traces.

**Comment by ungoldman** [comment]
Fixed in #56, released in [3.0.0](https://github.com/hypermodules/gh-release/releases/tag/v3.0.0).
