### ISSUE TITLE
Allow empty "unreleased" section

### ISSUE THREAD

**Issue by datenreisender** [hypermodules/gh-release#62]
We always keep an `unreleased` section in our `CHANGELOG.md`, it is just empty for releases. With #43 this is now prevented. It would be nice, if an empty `unreleased` section is allowed and only if there is stuff in it, an error is shown.

**Comment by ungoldman** [comment]
I see! I think if the `unreleased` is empty is makes sense to allow it.

I think all that would be needed is to modify the block linked to below to check if the unreleased section has a non-empty `body` property.

https://github.com/hypermodules/gh-release/blob/master/bin/lib/get-defaults.js#L22-L26

I will try to get this feature added soon, but in the meantime a PR is welcome 😄

**Comment by jrmykolyn** [comment]
@ungoldman @datenreisender 

Happy to take a crack at this?

**Comment by ungoldman** [comment]
@jrmykolyn please do if you have time 👍

**Comment by jrmykolyn** [comment]
Hey @ungoldman. I submitted PR #67 against this issue.

**Comment by ungoldman** [comment]
Thanks @jrmykolyn! This feature has been released in [`v3.2.0`](https://github.com/hypermodules/gh-release/releases/tag/v3.2.0).
