### ISSUE TITLE
Normalize Markdown headers

### ISSUE THREAD

**Issue by strugee** [hypermodules/gh-release#63]
In my changelogs I usually use `##` for each release and `###` for each section of the release, e.g.:

```markdown
# Changelog

Blah blah blah, semver semver, etc.

## 1.0.1

### Fixed

* Fixed the computer catching on fire when requiring this module

## 1.0.0

### Added

* Initial release
```

However in a GitHub Release I usually adjust these headers so they're all top-level `#`s since it doesn't really make sense to have a third-level header when there's no second-level or top-level headers. I.e. I'd love a feature where the body of 1.0.1 was normalized to:

```markdown
# Fixed

* Fixed the computer catching on fire when requiring this module
```

**Comment by ungoldman** [comment]
So there are a few issues with this request to my mind:

1. `gh-release` was designed to ensure each release matches the content of the change log for that version **exactly**.
2. Back in the day HTML documents were only supposed to have a single `h1` (`#`) tag denoting the title of the document. Now the usage is a little more liberal, but they're still only supposed to denote the title of an article or section.
3. The title of the release is itself already an `h1`:

<img width="328" alt="screen shot 2017-09-01 at 12 56 23 pm" src="https://user-images.githubusercontent.com/427322/29985716-003ba366-8f15-11e7-9249-6566f5a7825b.png">

Changing every heading in a release to be a `h1` seems like a step backward in terms of ensuring (a) generated content is semantic for screen readers and (b) release content matches change log content.

If you feel strongly about the style of the release content being different you can always edit it afterwards, but I'd humbly suggest you don't. Ideally git tags, change logs, and releases should all tell the same story.

**Comment by strugee** [comment]
Though I'd argue that in an ideal world, normalizing headers so they're semantic is GitHub's problem, practically I think you're right. I'd also argue that what's really important as long as the headers are the same level _in relation to each other_ the meaning is practically the same, but I guess that doesn't matter given the problem with the HTML's semantics.

So basically in conclusion, :thumbsup:
