### ISSUE TITLE
Catch `[Unreleased]` entries in `CHANGELOG.md`

### ISSUE THREAD

**Issue by jrmykolyn** [hypermodules/gh-release#65]
Currently, `get-defaults.js` will throw an error if it encounters a changelog entry/object with a title of 'Unreleased'. However, it will not error if encounters a title of '[Unreleased]'.

Since the [CHANGELOG.md](https://raw.githubusercontent.com/olivierlacan/keep-a-changelog/master/CHANGELOG.md) file @ [keep-a-changelog](https://github.com/olivierlacan/keep-a-changelog) includes brackets around the 'Unreleased' string, I thought this would be a useful update.

**Comment by jrmykolyn** [comment]
Hey @ungoldman. I submitted PR #66 against this issue.

**Comment by ungoldman** [comment]
Thanks again @jrmykolyn! Your PR has been merged and released in [`v3.1.2`](https://github.com/hypermodules/gh-release/releases/tag/v3.1.2).
