### ISSUE TITLE
Not working for github enterprise users

### ISSUE THREAD

**Issue by fr0** [hypermodules/gh-release#70]
The endpoint for a github enterprise server is `http://server/api/v3` instead of `https://api.github.com`.

The code in your library uses node's `url.resolve()` function to combine the endpoint url with `format('/repos/%s/%s/commits/%s', options.owner, options.repo, options.target_commitish)`

See: https://github.com/hypermodules/gh-release/blob/master/index.js#L79

However, the leading `/` (forward slash) overrides the `/api/v3` path, according to the rules of `url.resolve`. See:  https://nodejs.org/api/url.html#url_url_resolve_from_to

So, instead of:

```
http://server/api/v3/repos/user/repo/commits/commitish`
```
we get
```
http://server/repos/user/repo/commits/commitish`
```

which returns a 404.

(This pattern of using `url.resolve` is repeated elsewhere in the code).

**Comment by ungoldman** [comment]
Thanks for reporting @fr0! Fix welcome.

**Comment by ungoldman** [comment]
Resolved by https://github.com/hypermodules/gh-release/pull/73
