### ISSUE TITLE
Feature request: allow token from environment variable and add -y switch for avoiding prompt

### ISSUE THREAD

**Issue by tjaneczko** [hypermodules/gh-release#75]
We'd like to use gh-release through a CI/CD system (Jenkins). We can include a GitHub token as an environment variable, and would like to use that as we have some projects on github.com and some projects on an enterprise github (the current ghauth supports one or the other, not both).  Adding support for a `GH_RELEASE_GITHUB_TOKEN` environment variable would be perfect.  Additionally, we would want to bypass the yes/no prompt for actually performing the publish, so something like a `-y` switch would be perfect.

If this all sounds good, you can assign this to me, as I'll probably end up working on this soon.

**Comment by ungoldman** [comment]
These feature requests both sound totally reasonable!

Please feel free to tackle these issues.
