### ISSUE TITLE
Publish responds with [object Object],[object Object],[object Object], no release

### ISSUE THREAD

**Issue by rgwozdz** [hypermodules/gh-release#82]
Using gh-release v3.3.2 and node v 8.11.4 I find the following result:

```
? publish release to github? Yes
[object Object],[object Object],[object Object]
```

No release logged to Github.

**UPDATE**:  Added a console print of the actual error:
```
[ { resource: 'Release',
    code: 'custom',
    field: 'tag_name',
    message: 'tag_name is not a valid tag' },
  { resource: 'Release',
    code: 'custom',
    message: 'Published releases must have a valid tag' },
  { resource: 'Release',
    code: 'invalid',
    field: 'target_commitish' } ]
```

**Comment by jgravois** [comment]
@dbouwman encountered the same thing.

**Comment by ungoldman** [comment]
Sorry I haven't had a chance to look into this yet! If anyone wants to track down this bug I'd be mighty thankful. Will try to take a look as soon as I have some free time.

**Comment by ungoldman** [comment]
I think this bug must have been introduced in `v3.3.0` or later -- locking to `v3.2.3` may resolve the issue temporarily.

**Comment by rgwozdz** [comment]
Oddly, I only get this behavior on new repos which I have never used `gh-release` to do a release.  On repos that have been using `gh-release` in the past, I get the expected behavior.

**Comment by rgwozdz** [comment]
🤦‍♂️  Turns out the root of this problem (in my case) was my package.json had an outdated value for the `repository` property;  the repo was ported to a new org and open-sourced, and I had failed to update.

Thx @jgravois for getting me to poke at this some more.

**Comment by bcomnes** [comment]
Any opportunity to improve the error handling in this case?

**Comment by rgwozdz** [comment]
`repoParts` ([here](https://github.com/hypermodules/gh-release/blob/master/bin/lib/get-defaults.js#L14-L16)) was coming back `null` and causing the issue;  I can try to get to a PR in the coming days unless someone beats me to it.

**Comment by jgravois** [comment]
glad to hear it @rgwozdz! 

a previous attempt of mine to trap for that situation can be found in https://github.com/hypermodules/gh-release/pull/61

**Comment by tjaneczko** [comment]
@rgwozdz ended up taking a stab at this in #83 , hopefully that fixes the issue!

**Comment by ungoldman** [comment]
Thanks everyone for pitching in on this one! I really appreciate the community stepping in to help with maintenance :)

**Comment by tjaneczko** [comment]
Glad I could help out!!
