### ISSUE TITLE
Target commitish not found

### ISSUE THREAD

**Issue by zanedev** [hypermodules/gh-release#86]
Hi I'm using this with GH enterprise and I have set my `GH_RELEASE_GITHUB_API_TOKEN` env variable which appears to make it past the login step.  For some reason my commitish is not found even though the sha exists locally and on the remote server.  How can I troubleshoot this?

Command:

`GH_RELEASE_GITHUB_API_TOKEN=mytoken node_modules/gh-release/bin/cli.js -e https://myghenturl.com`

Output:

```
creating release v1.2.0 for myproject

name:               v1.2.0
tag_name:           v1.2.0
target_commitish:   cf51c1f8a23f7774cf8747716edb061e5b7990ac
endpoint:           https://myghenturl.com
body:               

### Features
- Initial release

? publish release to github? Yes
Error: Target commitish cf51c1f8a23f7774cf8747716edb061e5b7990ac not found in reponame

```

Commit exists remotely:

```
$ git ls-remote --heads --tags origin | grep cf51c1f8a23f7774cf8747716edb061e5b7990ac
$ cf51c1f8a23f7774cf8747716edb061e5b7990ac	refs/heads/mybranch
```

**Comment by zanedev** [comment]
Ok I debugged the `gh-release` code and the error message is unable to get local issuer certificate.  Not sure how to specify the issuer certificate since my `~/.npmrc` specifies a certificate and everything works locally otherwise when running outside of `gh-release`.

```
err:  { Error: unable to get local issuer certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:643:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }
Error: unable to get local issuer certificate
```

**Comment by zanedev** [comment]
Tried disabling git global check ssl and changed my remote to https no luck.

**Comment by zanedev** [comment]
hmm the same request with curl seems to work fine so it must be related to node request some how ok out of ideas 👍

**Comment by zanedev** [comment]
Fixed it for now by brute forcing node to not check the SSL.

`process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;`

I'm not sure there if there is a better way that would work for other people..  I'm behind a work proxy so it's probably doing funky things with the cert and disabling node strict_ssl globally didn't seem to work.

**Comment by bcomnes** [comment]
```console
NODE_TLS_REJECT_UNAUTHORIZED=0 gh-release
```

Would that work?

**Comment by zanedev** [comment]
Yeah that might do it thanks!
