### ISSUE TITLE
GitHub API Authorizations endpoint deprecated

### ISSUE THREAD

**Issue by paulcpederson** [hypermodules/gh-release#92]
When I recently released from an account with two factor auth I got a deprecation notice. It worked fine, but seems as though it won't work starting 2020?

> 
> You or an application you used recently accessed the deprecated Authorizations endpoint on the GitHub API with the useragent gh-release.
> 
> We will remove the Authorizations API endpoint on November 13, 2020. If you accessed the API via password authentication, then we recommend you use the web flow to authenticate. Please check that your app uses the web flow for authentication: https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#web-application-flow
> 
> You can learn more about these changes by visiting our developer blog:
> https://developer.github.com/changes/2020-02-14-deprecating-oauth-auth-endpoint/

**Comment by ungoldman** [comment]
yay

**Comment by paulcpederson** [comment]
This is very confusing, is web application flow even possible from the command line?

**Comment by bcomnes** [comment]
Woo change for changes sake.  My favorite. 

Yeah web flows are possible in CLI.  From memory, you show/open a url to the user, they open it in a browser, log in and click authorize, while the CLI polls in in the background at some token URL. When the flow in the browser completes, the CLI gets a token.

**Comment by bcomnes** [comment]
Going to take a look at this.

**Comment by bcomnes** [comment]
Draft PR: https://github.com/hypermodules/gh-release/pull/93

Not quite fixed yet, but baselined all the deps.
