### ISSUE TITLE
Switch to node-fetch from request

### ISSUE THREAD

**Issue by bcomnes** [hypermodules/gh-release#98]
Its lame request was depreciated, I mean why not just let it keep on keeping on.  But depreciated means unmaintained, so its worth switching over useful code to something that is maintained.  Node-fetch feels like a decent bet. 

Interested and willing to do this if people are cool with it.

**Comment by bcomnes** [comment]
Also just occurred to me, feross/simple-get might be a durable drop in replacement for request, which is more in line with the amount I would like to perform on this task.

**Comment by ungoldman** [comment]
fine by me. smaller footprint is a plus
